version: "2"
services:
  nginx:
    container_name: nginx
    image: nginx:1.19.8-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/conf.d/default.conf
      - ./files:/mnt/data
